Update jsonparse.js
Fix for this error:
Error: Unexpected "\u0000" at position 12251 in state STRING1

Looked up and turns out \u0000 means null character http://www.fileformat.info/info/unicode/char/0000/index.htm

So I added a check to ignore this character when parsing